### ISSUE TITLE
URGENT : please authorize public contribution to user khoja.medhi@gmail.com K-PANIK username

### ISSUE THREAD

**Issue by K-PANIK** [YansKhoja/TransfertStyle#5]
~/Documents/work/Deep-artist$ git push --set-upstream origin feature/clean_source_code
Username for 'https://github.com': khoja.medhi@gmail.com
Password for 'https://khoja.medhi@gmail.com@github.com': 
remote: Permission to YansKhoja/Deep-artist.git denied to K-PANIK.
fatal: unable to access 'https://github.com/YansKhoja/Deep-artist/': The requested URL returned error: 403

**Comment by YansKhoja** [comment]
done
